name: pysnippets
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # required
  - geofileops
  - geopandas-base
  - matplotlib
  - pyarrow-core
  - pygeoops
  - pyogrio
  #- pyshp
  #- qgis
  - rasterio
  - shapely
  # linting
  - ruff
