name: pysnippets
channels:
  #- gdal-master
  - conda-forge
dependencies:
  - python=3.13
  - pip
  # required
  - geofileops
  - geopandas-base
  - matplotlib
  - pyarrow-core
  - pygeoops
  - pyogrio
  #- pyshp
  #- qgis
  #- rasterio
  - shapely
  # linting
  - ruff
  # testing
  - pytest
