name: pysnippets
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # required
  - geofileops
  - geopandas
  - matplotlib
  - pyarrow
  - pygeoops
  - pyshp
  - qgis
  - rasterio
  - shapely
  # linting
  - black=23
  - ruff
  - pre-commit
